spring:
  cloud:
    config:
      server: 
        git:
          uri: https://github.com/orkhanmirzayev/config-repos
          search-paths:
          - app*
          force-pull: true

server: 
  port: 8084

security: 
  user: 
    name: admin
    password: admin
  basic:
    enabled: true
